/**
 * Tabela CFOP — Código Fiscal de Operações e Prestações
 * Fonte: CONFAZ / SINIEF
 */

export interface CfopEntry {
    code: string;
    description: string;
    type: 'saida' | 'entrada';
    scope: 'interno' | 'interestadual' | 'exterior';
}

export const CFOP_LIST: CfopEntry[] = [
    // ═══════════════════════════════════════════════════════════
    // SAÍDAS — OPERAÇÕES INTERNAS (5.XXX)
    // ═══════════════════════════════════════════════════════════
    { code: '5101', description: 'Venda de produção do estabelecimento', type: 'saida', scope: 'interno' },
    { code: '5102', description: 'Venda de mercadoria adquirida ou recebida de terceiros', type: 'saida', scope: 'interno' },
    { code: '5103', description: 'Venda de produção do estab. efetuada fora do estab.', type: 'saida', scope: 'interno' },
    { code: '5104', description: 'Venda de mercadoria adquirida efetuada fora do estab.', type: 'saida', scope: 'interno' },
    { code: '5110', description: 'Venda de mercadoria industrializada no estabelecimento', type: 'saida', scope: 'interno' },
    { code: '5111', description: 'Venda de produção do estab. sob regime de consignação', type: 'saida', scope: 'interno' },
    { code: '5112', description: 'Venda de mercadoria adquirida sob consignação mercantil', type: 'saida', scope: 'interno' },
    { code: '5113', description: 'Venda de produção para entrega futura', type: 'saida', scope: 'interno' },
    { code: '5114', description: 'Venda de mercadoria adquirida para entrega futura', type: 'saida', scope: 'interno' },
    { code: '5115', description: 'Venda de mercadoria adquirida recebida de terceiros em consignação', type: 'saida', scope: 'interno' },
    { code: '5116', description: 'Venda de produção do estab. originada de encomenda para entrega futura', type: 'saida', scope: 'interno' },
    { code: '5117', description: 'Venda de mercadoria adquirida originada de encomenda para entrega futura', type: 'saida', scope: 'interno' },
    { code: '5118', description: 'Venda de produção entregue ao destinatário por conta e ordem do adquirente originário', type: 'saida', scope: 'interno' },
    { code: '5119', description: 'Venda de mercadoria adquirida entregue ao destinatário pelo vendedor remetente', type: 'saida', scope: 'interno' },
    { code: '5120', description: 'Venda de mercadoria adquirida entregue ao destinatário sem transitar pelo estab.', type: 'saida', scope: 'interno' },
    { code: '5122', description: 'Venda de produção remetida para industrialização', type: 'saida', scope: 'interno' },
    { code: '5123', description: 'Venda de mercadoria adquirida remetida para industrialização', type: 'saida', scope: 'interno' },
    { code: '5124', description: 'Industrialização efetuada para outra empresa', type: 'saida', scope: 'interno' },
    { code: '5125', description: 'Industrialização efetuada para outra empresa quando a mercadoria for remetida pelo adquirente', type: 'saida', scope: 'interno' },
    { code: '5151', description: 'Transferência de produção do estabelecimento', type: 'saida', scope: 'interno' },
    { code: '5152', description: 'Transferência de mercadoria adquirida ou recebida de terceiros', type: 'saida', scope: 'interno' },
    { code: '5153', description: 'Transferência de energia elétrica', type: 'saida', scope: 'interno' },
    { code: '5155', description: 'Transferência de produção do estab. que não deva transitar pelo estab. depositante', type: 'saida', scope: 'interno' },
    { code: '5156', description: 'Transferência de mercadoria adquirida que não deva transitar pelo estab. depositante', type: 'saida', scope: 'interno' },
    { code: '5201', description: 'Devolução de compra para industrialização', type: 'saida', scope: 'interno' },
    { code: '5202', description: 'Devolução de compra para comercialização', type: 'saida', scope: 'interno' },
    { code: '5205', description: 'Anulação de valor relativo a aquisição de serviço de comunicação', type: 'saida', scope: 'interno' },
    { code: '5206', description: 'Anulação de valor relativo a aquisição de serviço de transporte', type: 'saida', scope: 'interno' },
    { code: '5207', description: 'Anulação de valor relativo à compra de energia elétrica', type: 'saida', scope: 'interno' },
    { code: '5208', description: 'Devolução de mercadoria recebida em transferência', type: 'saida', scope: 'interno' },
    { code: '5209', description: 'Devolução de mercadoria recebida em transferência para utilização na prestação de serviço', type: 'saida', scope: 'interno' },
    { code: '5210', description: 'Devolução de compra para utilização na prestação de serviço', type: 'saida', scope: 'interno' },
    { code: '5251', description: 'Venda de energia elétrica para distribuição ou comercialização', type: 'saida', scope: 'interno' },
    { code: '5252', description: 'Venda de energia elétrica para estab. industrial', type: 'saida', scope: 'interno' },
    { code: '5253', description: 'Venda de energia elétrica para estab. comercial', type: 'saida', scope: 'interno' },
    { code: '5254', description: 'Venda de energia elétrica para estab. prestador de serviço de transporte', type: 'saida', scope: 'interno' },
    { code: '5255', description: 'Venda de energia elétrica para estab. prestador de serviço de comunicação', type: 'saida', scope: 'interno' },
    { code: '5256', description: 'Venda de energia elétrica para estab. de produtor rural', type: 'saida', scope: 'interno' },
    { code: '5257', description: 'Venda de energia elétrica para consumo por demanda contratada', type: 'saida', scope: 'interno' },
    { code: '5258', description: 'Venda de energia elétrica a não contribuinte', type: 'saida', scope: 'interno' },
    { code: '5301', description: 'Prestação de serviço de comunicação', type: 'saida', scope: 'interno' },
    { code: '5302', description: 'Prestação de serviço de comunicação a estab. de produtor rural', type: 'saida', scope: 'interno' },
    { code: '5351', description: 'Prestação de serviço de transporte', type: 'saida', scope: 'interno' },
    { code: '5352', description: 'Prestação de serviço de transporte a estab. de produtor rural', type: 'saida', scope: 'interno' },
    { code: '5401', description: 'Venda de produção do estab. em operação com produto sujeito ao regime de ST', type: 'saida', scope: 'interno' },
    { code: '5402', description: 'Venda de produção do estab. de produto sujeito ao regime de ST', type: 'saida', scope: 'interno' },
    { code: '5403', description: 'Venda de mercadoria adquirida sujeita ao regime de ST', type: 'saida', scope: 'interno' },
    { code: '5405', description: 'Venda de mercadoria adquirida/recebida de terceiros sujeita a ST', type: 'saida', scope: 'interno' },
    { code: '5411', description: 'Devolução de compra para industrialização em oper. c/ mercadoria sujeita a ST', type: 'saida', scope: 'interno' },
    { code: '5412', description: 'Devolução de bem do ativo imobilizado em operação c/ ST', type: 'saida', scope: 'interno' },
    { code: '5413', description: 'Devolução de mercadoria destinada a uso ou consumo em operação c/ ST', type: 'saida', scope: 'interno' },
    { code: '5414', description: 'Devolução de compra para comercialização em operação c/ ST', type: 'saida', scope: 'interno' },
    { code: '5415', description: 'Devolução de compra para comercialização em operação sujeita a ST', type: 'saida', scope: 'interno' },
    { code: '5451', description: 'Remessa de animal e de insumo para estab. de produtor', type: 'saida', scope: 'interno' },
    { code: '5501', description: 'Remessa de produção do estab. com fim específico de exportação', type: 'saida', scope: 'interno' },
    { code: '5502', description: 'Remessa de mercadoria adquirida com fim específico de exportação', type: 'saida', scope: 'interno' },
    { code: '5551', description: 'Venda de bem do ativo imobilizado', type: 'saida', scope: 'interno' },
    { code: '5552', description: 'Transferência de bem do ativo imobilizado', type: 'saida', scope: 'interno' },
    { code: '5553', description: 'Devolução de compra de bem para o ativo imobilizado', type: 'saida', scope: 'interno' },
    { code: '5554', description: 'Remessa de bem do ativo imobilizado para uso fora do estab.', type: 'saida', scope: 'interno' },
    { code: '5555', description: 'Devolução de bem do ativo imobilizado de terceiro', type: 'saida', scope: 'interno' },
    { code: '5556', description: 'Devolução de compra de material de uso ou consumo', type: 'saida', scope: 'interno' },
    { code: '5557', description: 'Transferência de material de uso ou consumo', type: 'saida', scope: 'interno' },
    { code: '5601', description: 'Transferência de crédito de ICMS acumulado', type: 'saida', scope: 'interno' },
    { code: '5602', description: 'Transferência de saldo credor de ICMS para outro estab.', type: 'saida', scope: 'interno' },
    { code: '5603', description: 'Ressarcimento de ICMS retido por ST', type: 'saida', scope: 'interno' },
    { code: '5651', description: 'Venda de combustível ou lubrificante de produção do estab.', type: 'saida', scope: 'interno' },
    { code: '5652', description: 'Venda de combustível ou lubrificante adquiridos de terceiros', type: 'saida', scope: 'interno' },
    { code: '5653', description: 'Venda de combustível ou lubrificante a consumidor ou usuário final', type: 'saida', scope: 'interno' },
    { code: '5654', description: 'Venda de combustível ou lubrificante a estab. de transporte', type: 'saida', scope: 'interno' },
    { code: '5655', description: 'Venda de combustível ou lubrificante a estab. prestador de serviço comun.', type: 'saida', scope: 'interno' },
    { code: '5656', description: 'Venda de combustível ou lubrificante adq. ou recebidos de terceiros a consumidor final', type: 'saida', scope: 'interno' },
    { code: '5667', description: 'Venda de combustível ou lubrificante a consumidor ou usuário final estab. é contribuinte', type: 'saida', scope: 'interno' },
    { code: '5901', description: 'Remessa para industrialização por encomenda', type: 'saida', scope: 'interno' },
    { code: '5902', description: 'Retorno de mercadoria utilizada na industrialização por encomenda', type: 'saida', scope: 'interno' },
    { code: '5903', description: 'Retorno de mercadoria recebida para industrialização e não aplicada', type: 'saida', scope: 'interno' },
    { code: '5904', description: 'Remessa para venda fora do estabelecimento', type: 'saida', scope: 'interno' },
    { code: '5905', description: 'Remessa para depósito fechado ou armazém geral', type: 'saida', scope: 'interno' },
    { code: '5906', description: 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', type: 'saida', scope: 'interno' },
    { code: '5907', description: 'Retorno simbólico de mercadoria depositada em depósito fechado', type: 'saida', scope: 'interno' },
    { code: '5908', description: 'Remessa de bem por conta de contrato de comodato', type: 'saida', scope: 'interno' },
    { code: '5909', description: 'Retorno de bem recebido por conta de contrato de comodato', type: 'saida', scope: 'interno' },
    { code: '5910', description: 'Remessa em bonificação, doação ou brinde', type: 'saida', scope: 'interno' },
    { code: '5911', description: 'Remessa de amostra grátis', type: 'saida', scope: 'interno' },
    { code: '5912', description: 'Remessa de mercadoria ou bem para demonstração', type: 'saida', scope: 'interno' },
    { code: '5913', description: 'Retorno de mercadoria ou bem recebido para demonstração', type: 'saida', scope: 'interno' },
    { code: '5914', description: 'Remessa de mercadoria ou bem para exposição ou feira', type: 'saida', scope: 'interno' },
    { code: '5915', description: 'Remessa de mercadoria ou bem para conserto ou reparo', type: 'saida', scope: 'interno' },
    { code: '5916', description: 'Retorno de mercadoria ou bem recebido para conserto ou reparo', type: 'saida', scope: 'interno' },
    { code: '5917', description: 'Remessa de mercadoria em consignação mercantil ou industrial', type: 'saida', scope: 'interno' },
    { code: '5918', description: 'Devolução de mercadoria recebida em consignação', type: 'saida', scope: 'interno' },
    { code: '5919', description: 'Devolução simbólica de mercadoria vendida ou utilizada em processo industrial (consign.)', type: 'saida', scope: 'interno' },
    { code: '5920', description: 'Remessa de vasilhame ou sacaria', type: 'saida', scope: 'interno' },
    { code: '5921', description: 'Devolução de vasilhame ou sacaria', type: 'saida', scope: 'interno' },
    { code: '5922', description: 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', type: 'saida', scope: 'interno' },
    { code: '5923', description: 'Remessa de mercadoria por conta e ordem de terceiros', type: 'saida', scope: 'interno' },
    { code: '5924', description: 'Remessa para industrialização por conta e ordem do adquirente da mercadoria', type: 'saida', scope: 'interno' },
    { code: '5925', description: 'Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente', type: 'saida', scope: 'interno' },
    { code: '5929', description: 'Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento ECF', type: 'saida', scope: 'interno' },
    { code: '5932', description: 'Prestação de serviço de transporte iniciada em UF diversa daquela onde inscrito o prestador', type: 'saida', scope: 'interno' },
    { code: '5933', description: 'Prestação de serviço tributado pelo ISSQN', type: 'saida', scope: 'interno' },
    { code: '5934', description: 'Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado', type: 'saida', scope: 'interno' },
    { code: '5949', description: 'Outra saída de mercadoria ou prest. de serviço não especificada', type: 'saida', scope: 'interno' },

    // ═══════════════════════════════════════════════════════════
    // SAÍDAS — OPERAÇÕES INTERESTADUAIS (6.XXX)
    // ═══════════════════════════════════════════════════════════
    { code: '6101', description: 'Venda de produção do estabelecimento', type: 'saida', scope: 'interestadual' },
    { code: '6102', description: 'Venda de mercadoria adquirida ou recebida de terceiros', type: 'saida', scope: 'interestadual' },
    { code: '6103', description: 'Venda de produção do estab. efetuada fora do estab.', type: 'saida', scope: 'interestadual' },
    { code: '6104', description: 'Venda de mercadoria adquirida efetuada fora do estab.', type: 'saida', scope: 'interestadual' },
    { code: '6107', description: 'Venda de produção do estab. destinada a não contribuinte', type: 'saida', scope: 'interestadual' },
    { code: '6108', description: 'Venda de mercadoria adquirida destinada a não contribuinte', type: 'saida', scope: 'interestadual' },
    { code: '6109', description: 'Venda de produção do estab. destinada à ZFM ou ALC', type: 'saida', scope: 'interestadual' },
    { code: '6110', description: 'Venda de mercadoria adquirida destinada à ZFM ou ALC', type: 'saida', scope: 'interestadual' },
    { code: '6113', description: 'Venda de produção para entrega futura', type: 'saida', scope: 'interestadual' },
    { code: '6114', description: 'Venda de mercadoria adquirida para entrega futura', type: 'saida', scope: 'interestadual' },
    { code: '6116', description: 'Venda de produção originada de encomenda para entrega futura', type: 'saida', scope: 'interestadual' },
    { code: '6117', description: 'Venda de mercadoria adquirida originada de encomenda para entrega futura', type: 'saida', scope: 'interestadual' },
    { code: '6118', description: 'Venda de produção entregue ao destinatário por conta e ordem do adquirente originário', type: 'saida', scope: 'interestadual' },
    { code: '6119', description: 'Venda de mercadoria adquirida entregue ao destinatário pelo vendedor remetente', type: 'saida', scope: 'interestadual' },
    { code: '6120', description: 'Venda de mercadoria adquirida entregue ao destinatário sem transitar pelo estab.', type: 'saida', scope: 'interestadual' },
    { code: '6122', description: 'Venda de produção remetida para industrialização', type: 'saida', scope: 'interestadual' },
    { code: '6123', description: 'Venda de mercadoria adquirida remetida para industrialização', type: 'saida', scope: 'interestadual' },
    { code: '6124', description: 'Industrialização efetuada para outra empresa', type: 'saida', scope: 'interestadual' },
    { code: '6125', description: 'Industrialização efetuada para outra empresa quando a mercadoria for remetida pelo adquirente', type: 'saida', scope: 'interestadual' },
    { code: '6151', description: 'Transferência de produção do estabelecimento', type: 'saida', scope: 'interestadual' },
    { code: '6152', description: 'Transferência de mercadoria adquirida ou recebida de terceiros', type: 'saida', scope: 'interestadual' },
    { code: '6201', description: 'Devolução de compra para industrialização', type: 'saida', scope: 'interestadual' },
    { code: '6202', description: 'Devolução de compra para comercialização', type: 'saida', scope: 'interestadual' },
    { code: '6208', description: 'Devolução de mercadoria recebida em transferência', type: 'saida', scope: 'interestadual' },
    { code: '6209', description: 'Devolução de mercadoria recebida em transferência para utilização na prestação de serviço', type: 'saida', scope: 'interestadual' },
    { code: '6210', description: 'Devolução de compra para utilização na prestação de serviço', type: 'saida', scope: 'interestadual' },
    { code: '6401', description: 'Venda de produção do estab. em oper. c/ produto sujeito a ST', type: 'saida', scope: 'interestadual' },
    { code: '6403', description: 'Venda de mercadoria adquirida sujeita a ST', type: 'saida', scope: 'interestadual' },
    { code: '6501', description: 'Remessa de produção do estab. com fim específico de exportação', type: 'saida', scope: 'interestadual' },
    { code: '6502', description: 'Remessa de mercadoria adquirida com fim específico de exportação', type: 'saida', scope: 'interestadual' },
    { code: '6551', description: 'Venda de bem do ativo imobilizado', type: 'saida', scope: 'interestadual' },
    { code: '6552', description: 'Transferência de bem do ativo imobilizado', type: 'saida', scope: 'interestadual' },
    { code: '6553', description: 'Devolução de compra de bem para o ativo imobilizado', type: 'saida', scope: 'interestadual' },
    { code: '6556', description: 'Devolução de compra de material de uso ou consumo', type: 'saida', scope: 'interestadual' },
    { code: '6557', description: 'Transferência de material de uso ou consumo', type: 'saida', scope: 'interestadual' },
    { code: '6901', description: 'Remessa para industrialização por encomenda', type: 'saida', scope: 'interestadual' },
    { code: '6902', description: 'Retorno de mercadoria utilizada na industrialização por encomenda', type: 'saida', scope: 'interestadual' },
    { code: '6903', description: 'Retorno de mercadoria recebida para industrialização e não aplicada', type: 'saida', scope: 'interestadual' },
    { code: '6904', description: 'Remessa para venda fora do estabelecimento', type: 'saida', scope: 'interestadual' },
    { code: '6908', description: 'Remessa de bem por conta de contrato de comodato', type: 'saida', scope: 'interestadual' },
    { code: '6909', description: 'Retorno de bem recebido por conta de contrato de comodato', type: 'saida', scope: 'interestadual' },
    { code: '6910', description: 'Remessa em bonificação, doação ou brinde', type: 'saida', scope: 'interestadual' },
    { code: '6911', description: 'Remessa de amostra grátis', type: 'saida', scope: 'interestadual' },
    { code: '6912', description: 'Remessa de mercadoria ou bem para demonstração', type: 'saida', scope: 'interestadual' },
    { code: '6913', description: 'Retorno de mercadoria ou bem recebido para demonstração', type: 'saida', scope: 'interestadual' },
    { code: '6914', description: 'Remessa de mercadoria ou bem para exposição ou feira', type: 'saida', scope: 'interestadual' },
    { code: '6915', description: 'Remessa de mercadoria ou bem para conserto ou reparo', type: 'saida', scope: 'interestadual' },
    { code: '6916', description: 'Retorno de mercadoria ou bem recebido para conserto ou reparo', type: 'saida', scope: 'interestadual' },
    { code: '6917', description: 'Remessa de mercadoria em consignação', type: 'saida', scope: 'interestadual' },
    { code: '6918', description: 'Devolução de mercadoria recebida em consignação', type: 'saida', scope: 'interestadual' },
    { code: '6920', description: 'Remessa de vasilhame ou sacaria', type: 'saida', scope: 'interestadual' },
    { code: '6921', description: 'Devolução de vasilhame ou sacaria', type: 'saida', scope: 'interestadual' },
    { code: '6922', description: 'Simples faturamento de venda para entrega futura', type: 'saida', scope: 'interestadual' },
    { code: '6923', description: 'Remessa de mercadoria por conta e ordem de terceiros', type: 'saida', scope: 'interestadual' },
    { code: '6933', description: 'Prestação de serviço tributado pelo ISSQN', type: 'saida', scope: 'interestadual' },
    { code: '6949', description: 'Outra saída de mercadoria ou prest. de serviço não especificada', type: 'saida', scope: 'interestadual' },

    // ═══════════════════════════════════════════════════════════
    // SAÍDAS — OPERAÇÕES COM O EXTERIOR (7.XXX)
    // ═══════════════════════════════════════════════════════════
    { code: '7101', description: 'Venda de produção do estabelecimento', type: 'saida', scope: 'exterior' },
    { code: '7102', description: 'Venda de mercadoria adquirida ou recebida de terceiros', type: 'saida', scope: 'exterior' },
    { code: '7501', description: 'Exportação de mercadoria recebida com fim específico de exportação', type: 'saida', scope: 'exterior' },
    { code: '7551', description: 'Venda de bem do ativo imobilizado', type: 'saida', scope: 'exterior' },
    { code: '7949', description: 'Outra saída de mercadoria ou prest. de serviço não especificada', type: 'saida', scope: 'exterior' },

    // ═══════════════════════════════════════════════════════════
    // ENTRADAS — OPERAÇÕES INTERNAS (1.XXX)
    // ═══════════════════════════════════════════════════════════
    { code: '1101', description: 'Compra para industrialização', type: 'entrada', scope: 'interno' },
    { code: '1102', description: 'Compra para comercialização', type: 'entrada', scope: 'interno' },
    { code: '1111', description: 'Compra para industrialização de mercadoria recebida de terceiros', type: 'entrada', scope: 'interno' },
    { code: '1113', description: 'Compra para comercialização de mercadoria recebida de terceiros', type: 'entrada', scope: 'interno' },
    { code: '1116', description: 'Compra para industrialização originada de encomenda para recebimento futuro', type: 'entrada', scope: 'interno' },
    { code: '1117', description: 'Compra para comercialização originada de encomenda para recebimento futuro', type: 'entrada', scope: 'interno' },
    { code: '1118', description: 'Compra de mercadoria para comercialização pelo adquirente originário', type: 'entrada', scope: 'interno' },
    { code: '1120', description: 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador', type: 'entrada', scope: 'interno' },
    { code: '1121', description: 'Compra para comercialização em que a mercadoria foi remetida pelo fornecedor ao industrializador', type: 'entrada', scope: 'interno' },
    { code: '1122', description: 'Compra para industrialização sem transitar pelo estabelecimento', type: 'entrada', scope: 'interno' },
    { code: '1124', description: 'Industrialização efetuada por outra empresa', type: 'entrada', scope: 'interno' },
    { code: '1125', description: 'Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo foi adquirida por esta', type: 'entrada', scope: 'interno' },
    { code: '1126', description: 'Compra para utilização na prestação de serviço', type: 'entrada', scope: 'interno' },
    { code: '1128', description: 'Compra para utilização na prestação de serviço sujeita ao ISSQN', type: 'entrada', scope: 'interno' },
    { code: '1151', description: 'Transferência para industrialização', type: 'entrada', scope: 'interno' },
    { code: '1152', description: 'Transferência para comercialização', type: 'entrada', scope: 'interno' },
    { code: '1153', description: 'Transferência de energia elétrica', type: 'entrada', scope: 'interno' },
    { code: '1154', description: 'Transferência para utilização na prestação de serviço', type: 'entrada', scope: 'interno' },
    { code: '1201', description: 'Devolução de venda de produção do estabelecimento', type: 'entrada', scope: 'interno' },
    { code: '1202', description: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', type: 'entrada', scope: 'interno' },
    { code: '1203', description: 'Anulação de valor relativo à prestação de serviço de comunicação', type: 'entrada', scope: 'interno' },
    { code: '1204', description: 'Anulação de valor relativo à prestação de serviço de transporte', type: 'entrada', scope: 'interno' },
    { code: '1205', description: 'Anulação de valor relativo à venda de energia elétrica', type: 'entrada', scope: 'interno' },
    { code: '1206', description: 'Anulação de valor relativo à venda de mercadoria sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1207', description: 'Devolução de produção do estab. remetida em transferência', type: 'entrada', scope: 'interno' },
    { code: '1208', description: 'Devolução de mercadoria adquirida/recebida remetida em transferência', type: 'entrada', scope: 'interno' },
    { code: '1209', description: 'Devolução de mercadoria remetida em transferência para utilização em serviço', type: 'entrada', scope: 'interno' },
    { code: '1251', description: 'Compra de energia elétrica para distribuição ou comercialização', type: 'entrada', scope: 'interno' },
    { code: '1252', description: 'Compra de energia elétrica por estab. industrial', type: 'entrada', scope: 'interno' },
    { code: '1253', description: 'Compra de energia elétrica por estab. comercial', type: 'entrada', scope: 'interno' },
    { code: '1254', description: 'Compra de energia elétrica por prestador de serviço de transporte', type: 'entrada', scope: 'interno' },
    { code: '1255', description: 'Compra de energia elétrica por prestador de serviço de comunicação', type: 'entrada', scope: 'interno' },
    { code: '1256', description: 'Compra de energia elétrica por estab. de produtor rural', type: 'entrada', scope: 'interno' },
    { code: '1257', description: 'Compra de energia elétrica para consumo por demanda contratada', type: 'entrada', scope: 'interno' },
    { code: '1301', description: 'Aquisição de serviço de comunicação', type: 'entrada', scope: 'interno' },
    { code: '1351', description: 'Aquisição de serviço de transporte', type: 'entrada', scope: 'interno' },
    { code: '1401', description: 'Compra para industrialização em oper. c/ mercadoria sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1403', description: 'Compra para comercialização em oper. c/ mercadoria sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1406', description: 'Compra de bem para o ativo imobilizado c/ merc. sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1407', description: 'Compra de mercadoria para uso ou consumo c/ merc. sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1408', description: 'Transferência para industrialização em oper. c/ merc. sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1409', description: 'Transferência para comercialização em oper. c/ merc. sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1410', description: 'Devolução de venda de produção do estab. em oper. c/ ST', type: 'entrada', scope: 'interno' },
    { code: '1411', description: 'Devolução de venda de mercadoria adquirida sujeita a ST', type: 'entrada', scope: 'interno' },
    { code: '1414', description: 'Retorno de produção do estab. remetida para venda fora do estab. em oper. c/ ST', type: 'entrada', scope: 'interno' },
    { code: '1415', description: 'Retorno de mercadoria adquirida remetida para venda fora do estab. em oper. c/ ST', type: 'entrada', scope: 'interno' },
    { code: '1451', description: 'Retorno de animal remetido a estab. de produtor', type: 'entrada', scope: 'interno' },
    { code: '1501', description: 'Entrada de mercadoria recebida com fim específico de exportação', type: 'entrada', scope: 'interno' },
    { code: '1551', description: 'Compra de bem para o ativo imobilizado', type: 'entrada', scope: 'interno' },
    { code: '1552', description: 'Transferência de bem do ativo imobilizado', type: 'entrada', scope: 'interno' },
    { code: '1553', description: 'Devolução de venda de bem do ativo imobilizado', type: 'entrada', scope: 'interno' },
    { code: '1554', description: 'Retorno de bem do ativo imobilizado remetido para uso fora do estab.', type: 'entrada', scope: 'interno' },
    { code: '1555', description: 'Entrada de bem do ativo imobilizado de terceiro remetido para uso no estab.', type: 'entrada', scope: 'interno' },
    { code: '1556', description: 'Compra de material para uso ou consumo', type: 'entrada', scope: 'interno' },
    { code: '1557', description: 'Transferência de material para uso ou consumo', type: 'entrada', scope: 'interno' },
    { code: '1601', description: 'Recebimento por transferência de crédito de ICMS', type: 'entrada', scope: 'interno' },
    { code: '1602', description: 'Recebimento por transferência de saldo credor de ICMS de outro estab.', type: 'entrada', scope: 'interno' },
    { code: '1603', description: 'Ressarcimento de ICMS retido por ST', type: 'entrada', scope: 'interno' },
    { code: '1651', description: 'Compra de combustível ou lubrificante para industrialização subsequente', type: 'entrada', scope: 'interno' },
    { code: '1652', description: 'Compra de combustível ou lubrificante para comercialização', type: 'entrada', scope: 'interno' },
    { code: '1653', description: 'Compra de combustível ou lubrificante por consumidor ou usuário final', type: 'entrada', scope: 'interno' },
    { code: '1658', description: 'Transferência de combustível e lubrificante para industrialização', type: 'entrada', scope: 'interno' },
    { code: '1659', description: 'Transferência de combustível e lubrificante para comercialização', type: 'entrada', scope: 'interno' },
    { code: '1660', description: 'Devolução de venda de combustível ou lubrificante destinado à industrialização', type: 'entrada', scope: 'interno' },
    { code: '1661', description: 'Devolução de venda de combustível ou lubrificante destinado à comercialização', type: 'entrada', scope: 'interno' },
    { code: '1662', description: 'Devolução de venda de combustível ou lubrificante destinado a consumidor ou usuário final', type: 'entrada', scope: 'interno' },
    { code: '1901', description: 'Entrada para industrialização por encomenda', type: 'entrada', scope: 'interno' },
    { code: '1902', description: 'Retorno de mercadoria remetida para industrialização por encomenda', type: 'entrada', scope: 'interno' },
    { code: '1903', description: 'Entrada de mercadoria remetida para industrialização e não aplicada no referido processo', type: 'entrada', scope: 'interno' },
    { code: '1904', description: 'Retorno de remessa para venda fora do estabelecimento', type: 'entrada', scope: 'interno' },
    { code: '1905', description: 'Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral', type: 'entrada', scope: 'interno' },
    { code: '1906', description: 'Retorno de mercadoria remetida para depósito fechado ou armazém geral', type: 'entrada', scope: 'interno' },
    { code: '1907', description: 'Retorno simbólico de mercadoria remetida para depósito fechado', type: 'entrada', scope: 'interno' },
    { code: '1908', description: 'Entrada de bem por conta de contrato de comodato', type: 'entrada', scope: 'interno' },
    { code: '1909', description: 'Retorno de bem remetido por conta de contrato de comodato', type: 'entrada', scope: 'interno' },
    { code: '1910', description: 'Entrada de bonificação, doação ou brinde', type: 'entrada', scope: 'interno' },
    { code: '1911', description: 'Entrada de amostra grátis', type: 'entrada', scope: 'interno' },
    { code: '1912', description: 'Entrada de mercadoria ou bem recebido para demonstração', type: 'entrada', scope: 'interno' },
    { code: '1913', description: 'Retorno de mercadoria ou bem remetido para demonstração', type: 'entrada', scope: 'interno' },
    { code: '1914', description: 'Retorno de mercadoria ou bem remetido para exposição ou feira', type: 'entrada', scope: 'interno' },
    { code: '1915', description: 'Entrada de mercadoria ou bem recebido para conserto ou reparo', type: 'entrada', scope: 'interno' },
    { code: '1916', description: 'Retorno de mercadoria ou bem remetido para conserto ou reparo', type: 'entrada', scope: 'interno' },
    { code: '1917', description: 'Entrada de mercadoria recebida em consignação', type: 'entrada', scope: 'interno' },
    { code: '1918', description: 'Devolução de mercadoria remetida em consignação', type: 'entrada', scope: 'interno' },
    { code: '1919', description: 'Devolução simbólica de mercadoria vendida ou utilizada em processo ind. (consign.)', type: 'entrada', scope: 'interno' },
    { code: '1920', description: 'Entrada de vasilhame ou sacaria', type: 'entrada', scope: 'interno' },
    { code: '1921', description: 'Retorno de vasilhame ou sacaria', type: 'entrada', scope: 'interno' },
    { code: '1922', description: 'Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro', type: 'entrada', scope: 'interno' },
    { code: '1923', description: 'Entrada de mercadoria recebida do vendedor remetente', type: 'entrada', scope: 'interno' },
    { code: '1926', description: 'Lançamento efetuado a título de reclassificação de mercadoria', type: 'entrada', scope: 'interno' },
    { code: '1933', description: 'Aquisição de serviço tributado pelo ISSQN', type: 'entrada', scope: 'interno' },
    { code: '1934', description: 'Entrada simbólica de mercadoria recebida para depósito fechado ou armazém geral', type: 'entrada', scope: 'interno' },
    { code: '1949', description: 'Outra entrada de mercadoria ou prest. de serviço não especificada', type: 'entrada', scope: 'interno' },

    // ═══════════════════════════════════════════════════════════
    // ENTRADAS — INTERESTADUAIS (2.XXX) — resumo
    // ═══════════════════════════════════════════════════════════
    { code: '2101', description: 'Compra para industrialização', type: 'entrada', scope: 'interestadual' },
    { code: '2102', description: 'Compra para comercialização', type: 'entrada', scope: 'interestadual' },
    { code: '2126', description: 'Compra para utilização na prestação de serviço', type: 'entrada', scope: 'interestadual' },
    { code: '2151', description: 'Transferência para industrialização', type: 'entrada', scope: 'interestadual' },
    { code: '2152', description: 'Transferência para comercialização', type: 'entrada', scope: 'interestadual' },
    { code: '2201', description: 'Devolução de venda de produção do estabelecimento', type: 'entrada', scope: 'interestadual' },
    { code: '2202', description: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', type: 'entrada', scope: 'interestadual' },
    { code: '2551', description: 'Compra de bem para o ativo imobilizado', type: 'entrada', scope: 'interestadual' },
    { code: '2556', description: 'Compra de material para uso ou consumo', type: 'entrada', scope: 'interestadual' },
    { code: '2901', description: 'Entrada para industrialização por encomenda', type: 'entrada', scope: 'interestadual' },
    { code: '2902', description: 'Retorno de mercadoria remetida para industrialização por encomenda', type: 'entrada', scope: 'interestadual' },
    { code: '2910', description: 'Entrada de bonificação, doação ou brinde', type: 'entrada', scope: 'interestadual' },
    { code: '2949', description: 'Outra entrada de mercadoria ou prest. de serviço não especificada', type: 'entrada', scope: 'interestadual' },

    // ═══════════════════════════════════════════════════════════
    // ENTRADAS — EXTERIOR (3.XXX)
    // ═══════════════════════════════════════════════════════════
    { code: '3101', description: 'Compra para industrialização', type: 'entrada', scope: 'exterior' },
    { code: '3102', description: 'Compra para comercialização', type: 'entrada', scope: 'exterior' },
    { code: '3126', description: 'Compra para utilização na prestação de serviço', type: 'entrada', scope: 'exterior' },
    { code: '3127', description: 'Compra para industrialização sob o regime de drawback', type: 'entrada', scope: 'exterior' },
    { code: '3201', description: 'Devolução de venda de produção do estabelecimento', type: 'entrada', scope: 'exterior' },
    { code: '3202', description: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', type: 'entrada', scope: 'exterior' },
    { code: '3551', description: 'Compra de bem para o ativo imobilizado', type: 'entrada', scope: 'exterior' },
    { code: '3556', description: 'Compra de material para uso ou consumo', type: 'entrada', scope: 'exterior' },
    { code: '3949', description: 'Outra entrada de mercadoria ou prest. de serviço não especificada', type: 'entrada', scope: 'exterior' },
];
